title: jekyll-bootstrap4-grid Example
brand: jekyll-bootstrap4-grid
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Example of jekyll-bootstra4-grid plugin

baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://example.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

permalink: ./example/:title

exclude:
  - node_modules
  - README.md
  - package.json
  - Gemfile
  - Gemfile.lock
  - LICENSE
